#!/bin/sh
#
# SOOS DAST DigitalOcean Droplet

cat <<EOF
********************************************************************************

Welcome to SOOS.io's DigitalOcean 1-Click DAST Droplet.

This droplet has installed the latest SOOS DAST docker image.

Configure a scan by running the following commands:

cd /usr/soos
./configure-soos-dast.sh

The configuration script will save a reusable run script to the /usr/soos/ directory.

You will need your client id and API key from the SOOS website to configure a scan.

https://app.soos.io/integrate/dast

For more help and information, visit https://kb.soos.io

Thank you!
SOOS

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF